# Generated by Django 3.0.4 on 2020-05-05 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreActividad', models.CharField(max_length=200, verbose_name='Nombre de Actividad')),
                ('descripcion', models.TextField(default=None, verbose_name='Descripción de Actividad')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Chab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chab', models.IntegerField(verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Año',
                'verbose_name_plural': 'Años',
            },
        ),
        migrations.CreateModel(
            name='Cuatrimestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCuatrimestre', models.CharField(max_length=25, verbose_name='Cuatrimestre')),
            ],
            options={
                'verbose_name': 'Cuatrimestre',
                'verbose_name_plural': 'Cuatrimestres',
            },
        ),
        migrations.CreateModel(
            name='Epoca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEpoca', models.CharField(max_length=25, verbose_name='Época')),
            ],
            options={
                'verbose_name': 'Época del año',
                'verbose_name_plural': 'Épocas del año',
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFase', models.CharField(max_length=25, verbose_name='Fase Lunar')),
                ('imagenFase', models.ImageField(default=None, upload_to='qamar_images', verbose_name='Fase Lunar')),
            ],
            options={
                'verbose_name': 'Fase lunar',
                'verbose_name_plural': 'Fases lunares',
            },
        ),
        migrations.CreateModel(
            name='Tiempo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTiempo', models.CharField(max_length=25, verbose_name='Tiempo')),
            ],
            options={
                'verbose_name': 'Tiempo del año',
                'verbose_name_plural': 'Tiempos del año',
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoActividad', models.CharField(max_length=200, verbose_name='Tipo de Actividad')),
            ],
            options={
                'verbose_name': 'Tipo de actividad',
                'verbose_name_plural': 'Tipos de actividades',
            },
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMes', models.CharField(max_length=15, verbose_name='Mes')),
                ('idCuatrimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qamar.Cuatrimestre', verbose_name='Cuatrimestre')),
                ('idEpoca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qamar.Epoca', verbose_name='Época del año')),
                ('idTiempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qamar.Tiempo', verbose_name='Tiempo del año')),
            ],
            options={
                'verbose_name': 'Mes',
                'verbose_name_plural': 'Meses',
            },
        ),
        migrations.CreateModel(
            name='LunaMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.IntegerField(verbose_name='Fecha Lunar')),
                ('idChab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qamar.Chab', verbose_name='Año')),
                ('idFase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qamar.Fase', verbose_name='Fase Lunar')),
                ('idMes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qamar.Mes', verbose_name='Mes')),
            ],
            options={
                'verbose_name': 'Fecha lunar',
                'verbose_name_plural': 'Fechas lunares',
            },
        ),
        migrations.CreateModel(
            name='LunaActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qamar.Actividad', verbose_name='Actividad')),
                ('idFecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qamar.LunaMes', verbose_name='Fecha Lunar')),
            ],
            options={
                'verbose_name': 'Activad por fecha',
                'verbose_name_plural': 'Actividades por fecha',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='idTipoActividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qamar.TipoActividad', verbose_name='Tipo de Actividad'),
        ),
    ]
