# Generated by Django 3.0.4 on 2020-05-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qamar', '0002_auto_20200505_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='chab',
            name='imagenChab',
            field=models.ImageField(default=None, upload_to='qamar_images', verbose_name='Imagen de Cargador'),
        ),
    ]
