# Generated by Django 3.0.4 on 2020-05-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qamar', '0003_chab_imagenchab'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogosPieDePagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLogo', models.CharField(max_length=25, verbose_name='Nombre de Logo')),
                ('imagenLogo', models.ImageField(default=None, upload_to='qamar_images', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Logo pie de página',
                'verbose_name_plural': 'Logos pie de página',
            },
        ),
    ]
