# Generated by Django 3.0.4 on 2020-03-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qamar', '0003_auto_20200318_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(default=None, verbose_name='Descripción de Actividad'),
        ),
    ]
