# Generated by Django 3.0.4 on 2020-03-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qamar', '0005_auto_20200318_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mes',
            options={'verbose_name': 'Mes', 'verbose_name_plural': 'Meses'},
        ),
    ]
