# Generated by Django 3.0.4 on 2020-03-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qamar', '0006_auto_20200319_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='chab',
            options={'verbose_name': 'Año', 'verbose_name_plural': 'Años'},
        ),
        migrations.AlterModelOptions(
            name='cuatrimestre',
            options={'verbose_name': 'Cuatrimestre', 'verbose_name_plural': 'Cuatrimestres'},
        ),
        migrations.AlterModelOptions(
            name='fase',
            options={'verbose_name': 'Fase lunar', 'verbose_name_plural': 'Fases lunares'},
        ),
        migrations.AlterModelOptions(
            name='lunaactividad',
            options={'verbose_name': 'Activad por fecha', 'verbose_name_plural': 'Actividades por fecha'},
        ),
        migrations.AlterModelOptions(
            name='lunames',
            options={'verbose_name': 'Fecha lunar', 'verbose_name_plural': 'Fechas lunares'},
        ),
        migrations.AlterModelOptions(
            name='tiempo',
            options={'verbose_name': 'Tiempo del año', 'verbose_name_plural': 'Tiempos del año'},
        ),
        migrations.AlterModelOptions(
            name='tipoactividad',
            options={'verbose_name': 'Tipo de actividad', 'verbose_name_plural': 'Tipos de actividades'},
        ),
    ]
