# Generated by Django 3.0.4 on 2020-05-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qamar', '0007_auto_20200319_1053'),
        ('qamar', '0004_logospiedepagina'),
    ]

    operations = [
    ]
