# Generated by Django 3.0.4 on 2020-05-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qamar', '0008_merge_20200527_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logospiedepagina',
            name='nombreLogo',
            field=models.CharField(max_length=200, verbose_name='Nombre de Logo'),
        ),
    ]
